export const projects = [
  {
    title: 'WedLoc',
    description:
      "WedLoc is not just another wedding platform; it's a one-of-a-kind social hub designed exclusively for wedding photographers and videographers. Our mission is to provide a seamless space for professionals to organize and showcase wedding media, making it easy for couples and guests to relive their special moments. With added features like media comments and real-time chat, we've eliminated the need for attendees to sign up, making the entire experience hassle-free.",
    image: './assets/img/wedloc.png',
    repository: 'https://github.com/markthos/wedloc',
    deployment: 'https://wedloc-84c89e3ae29d.herokuapp.com/',
    techstack: [
      'React',
      'MongoDB',
      'GraphQL',
      'NodeJS',
      'ExpressJS',
      'Tailwind CSS',
      'Cloudinary',
      'Heroku',
      'Mongoose',
      'Axios',
      'Material UI',
      'React Router',
      'Stripe',
      'Figma',
      'Animate On Scroll',
      'JWT',
      'Socket IO',
    ],
    completed: 'October 2023',
    featured: true,
  },
  {
    title: 'Task Titan',
    description:
      'A website where you can create, track, edit, delete, and complete tasks. Use Task Titan to CRUSH your tasks to build awesome projects!',
    image: './assets/img/tasktitan.png',
    repository: 'https://github.com/markthos/Task-Titan',
    deployment: 'https://task-titan-bec51c55ebe5.herokuapp.com/',
    techstack: [
      'HTML',
      'CSS',
      'JavaScript',
      'NodeJS',
      'ExpressJS',
      'MySQL',
      'Sequelize',
      'Handlebars',
      'Materialize CSS',
      'Dragula',
      'Socket IO',
    ],
    completed: 'August 2023',
    featured: true,
  },
  {
    title: 'Loot Vault',
    description:
      'A website for gamers on a budget! With a responsive design and easy to use navigation, you can find any game you want at the best prices!',
    image: './assets/img/lootVault.png',
    repository: 'https://github.com/Torvec/project_1_Loot_Vault',
    deployment: 'https://torvec.github.io/project_1_Loot_Vault/',
    techstack: [
      'HTML',
      'CSS',
      'JavaScript',
      'Bulma CSS',
      'DayJS',
      'RAWG API',
      'CheapShark API',
      'Gamepower Free Games API',
    ],
    completed: 'June 2023',
    featured: true,
  },
  {
    title: 'UC Berkeley Bootcamp Challenges',
    description:
      'All of my individual challenges from the UC Berkeley Full Stack Web Development Bootcamp.',
    image: './assets/img/lootVault.png',
    repository: 'https://github.com/Torvec/bootcamp-challenges',
    deployment: 'https://torvec.github.io/bootcamp_challenges/',
    techstack: [
      'HTML',
      'CSS',
      'JavaScript',
      'Bulma CSS',
      'DayJS',
      'RAWG API',
      'CheapShark API',
      'Gamepower Free Games API',
    ],
    completed: 'October 2023',
    featured: false,
  },
];
